# -*- coding: utf-8 -*-
"""hw1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aWcEBfhCeDjBIqzWzXGNwD8z2clHIdfv

Import the numpy package under the name np
"""

import numpy as np

"""Create a vector or 1D array with 10 zeros and print it"""

x = np.zeros(10)
print (x)

"""Find the memory size of this array"""

print ("%d bytes" % (x.size * x.itemsize))

"""Create another vector or 1D array with values ranging from 10 to 20"""

x = np.arange(10, 21)
print (x)

"""Reverse the created vector (first element becomes last) -- Is there any NumPy method that you can use?"""

np.flip(x)

"""Create a 3x4 array with random values (standard normal distribution) and find the minimum and maximum values"""

x = np.random.randn(3, 4)
min, max = x.min(), x.max()
print(x, '\n', min, '\n', max)

"""Given the following 1D array, negate all elements which are between 3 and 8, in place. (include both 3 and 8 in conditional statements)"""

x = np.arange(11)

x[(3 <= x) & (8 >= x)] *= -1
print(x)

"""Given the 1D array Z, find the closest value to the given scalar v?"""

Z = np.arange(5, 100)
v = np.array(33.2)

index = (np.abs(Z-v)).argmin()
print(Z[index])

"""Subtract the mean of each row of the following matrix"""

np.random.seed(2)
X = np.random.rand(3, 4)
print(X)

Y = X - X.mean(axis=1, keepdims=True)
print(Y)

"""Timing comparison for multiplication of 4 arrays. Find the fastest way to compute the multiplication ABCD. Make sure you report the elapsed time. (hint: you can find relevant information at https://youtu.be/SeBRHg9ZrSs)"""

A = np.random.random((10000,1000))
B = np.random.random((1000,10000))
C = np.random.random((10000,5))
D = np.random.random((5,1000))

import time

beginning = time.time()
np.linalg.multi_dot([A, B, C, D])
end = time.time()

runTime = end - beginning
print(runTime)

"""Import and print the file 'parks.csv' (Park Code should be the index column)"""

from google.colab import files
data_to_load = files.upload()

import pandas as pd

df = pd.read_csv('parks.csv', index_col=['Park Code'])
df

"""Print all column names"""

print(df.columns)

"""Make sure tha all letters are lower case and replace space with _"""

df.columns = [col.replace(' ', '_').lower() for col in df.columns]
print(df.columns)

"""Which state has the smallest national park?"""

df['state'][df['acres'].argmin()]

"""Produce a histogram plot that shows the distribution of 'acres'. """

df.hist(column='acres')

